'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  READY_GRID_COLUMNS,
  isReadyGridSortable,
  type ReadyGridColumn,
  type ReadyGridColumnKey,
} from './ready-grid-layout';

/**
 * The five per-family layout fields this used to carry (`template`, `cellClass`,
 * `rowShellClass`, `frozenCellClass`, `frozenLeft`, `isFrozen`) are gone: each
 * was a family-flavoured alias of the same shared function, and
 * `LedgerHeaderLayoutApi`'s docblock records why they were collapsed. What is
 * genuinely per-family is which columns sort and where the frozen edge sits.
 */
const READY_HEADER_LAYOUT: LedgerHeaderLayoutApi = {
  isSortable: isReadyGridSortable,
  // Read-only browse: only the select gutter is frozen, so the scroll-edge cue
  // hangs there — the Sheets-class arrangement every house grid shares.
  frozenEdgeKey: 'select',
};

/**
 * Sticky column header for the Ready LedgerGrid. Read-only browse — the empty
 * `select` gutter keeps the frozen product cell aligned with every house grid.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const ReadyGridColumnHeader = makeLedgerGridColumnHeader<
  ReadyGridColumn,
  ReadyGridColumnKey
>({
  layout: READY_HEADER_LAYOUT,
  defaultColumns: READY_GRID_COLUMNS,
  tableId: 'ready',
});
