'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  READY_GRID_COLUMNS,
  READY_GRID_FROZEN_CELL,
  isReadyGridFrozen,
  isReadyGridSortable,
  readyGridCell,
  readyGridFrozenLeft,
  readyGridRowShellClass,
  readyGridTemplate,
  type ReadyGridColumn,
  type ReadyGridColumnKey,
} from './ready-grid-layout';

const READY_HEADER_LAYOUT: LedgerHeaderLayoutApi<ReadyGridColumn> = {
  template: readyGridTemplate,
  cellClass: readyGridCell,
  rowShellClass: readyGridRowShellClass,
  frozenCellClass: READY_GRID_FROZEN_CELL,
  frozenLeft: (key) => readyGridFrozenLeft(key as ReadyGridColumnKey),
  isFrozen: isReadyGridFrozen,
  isSortable: isReadyGridSortable,
};

/**
 * Sticky column header for the Ready LedgerGrid. Read-only browse — the empty
 * `select` gutter keeps the frozen product cell aligned with every house grid.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const ReadyGridColumnHeader = makeLedgerGridColumnHeader<
  ReadyGridColumn,
  ReadyGridColumnKey
>({
  layout: READY_HEADER_LAYOUT,
  defaultColumns: READY_GRID_COLUMNS,
  tableId: 'ready',
});
