/** Loss write-off — the terminal answer for a carrier-delivered carton whose goods never physically materialized (Phase 3 of… */

import type { OrgId } from '@/lib/tenancy/constants';
// TYPE-only: `./exceptions` reaches `@/lib/tenancy/db` (`server-only`) at module load, which would make this module unimportable from a…
import type { recordReceivingException, resolveReceivingExceptions } from './exceptions';
import {
  LOSS_EXCEPTION_CODES,
  RECEIVING_EXCEPTION_META,
  isLossExceptionCode,
} from './exception-codes';

/** Exported for the resolution route's 400 discriminator and its test. */
export const LOSS_WRITEOFF_INVALID_CODE = 'INVALID_LOSS_CODE';

/** Cap on the operator note (the column is unbounded `text`). */
const MAX_NOTE_LENGTH = 500;

/** Cap on the server-assembled reason. */
const MAX_REASON_LENGTH = 500;

type LossCode = (typeof LOSS_EXCEPTION_CODES)[number];

type LossCodeParse =
  /** No code supplied — a write-off with no stated kind is never accepted. */
  | { state: 'absent' }
  | { state: 'valid'; code: LossCode }
  /** Present but outside the loss vocabulary (incl. a valid OS&D code). */
  | { state: 'invalid' };

/** Classify the raw body value. */
export function parseLossCode(raw: unknown): LossCodeParse {
  if (raw === undefined || raw === null) return { state: 'absent' };
  if (typeof raw !== 'string') return { state: 'invalid' };
  const trimmed = raw.trim();
  if (trimmed === '') return { state: 'absent' };
  // Narrow guard on purpose: `isReceivingExceptionCode` would accept 'SHORT', and
  // an OS&D code must not be usable to write a carton off.
  if (!isLossExceptionCode(trimmed)) return { state: 'invalid' };
  return { state: 'valid', code: trimmed };
}

/** 400 body for a code outside the loss vocabulary — echoes the allowed set. */
export function lossWriteoffInvalidBody(): {
  success: false;
  error: typeof LOSS_WRITEOFF_INVALID_CODE;
  allowed: readonly LossCode[];
} {
  return { success: false, error: LOSS_WRITEOFF_INVALID_CODE, allowed: LOSS_EXCEPTION_CODES };
}

/** Trim + cap an optional operator note; blank becomes null. */
export function normalizeLossNote(raw: unknown): string | null {
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim();
  if (trimmed === '') return null;
  return trimmed.length > MAX_NOTE_LENGTH
    ? `${trimmed.slice(0, MAX_NOTE_LENGTH - 1)}…`
    : trimmed;
}

/**
 * Canonical "what was written off", assembled from the validated code and the
 * carton's delivery facts. Server-generated by construction.
 */
function lossWriteoffReason(code: LossCode, deliveredAt: string | null): string {
  const label = RECEIVING_EXCEPTION_META[code].label;
  const when = deliveredAt ? ` (carrier delivered ${deliveredAt})` : '';
  const text = `Written off at receiving: ${label}${when}`;
  return text.length > MAX_REASON_LENGTH ? `${text.slice(0, MAX_REASON_LENGTH - 1)}…` : text;
}

interface RecordLossWriteoffInput {
  /** REQUIRED — never defaulted; see the module header. */
  code: LossCode;
  receivingLineId: number;
  receivingId: number | null;
  /** Carrier delivery instant, for the server-assembled reason text. */
  deliveredAt?: string | null;
  /** Optional bounded operator evidence — never the justification. */
  note?: string | null;
  staffId: number | null;
}

interface LossWriteoffDeps {
  recordException: typeof recordReceivingException;
  resolveExceptions: typeof resolveReceivingExceptions;
}

/** Resolve the real writers on first use — see the type-only import above. */
async function realDeps(): Promise<LossWriteoffDeps> {
  const mod = await import('./exceptions');
  return {
    recordException: mod.recordReceivingException,
    resolveExceptions: mod.resolveReceivingExceptions,
  };
}

/**
 * Persist the write-off as ONE open `receiving_exceptions` row. The shared waist
 * emits the `exception_why` entity signal for free; the route audits separately, so
 * the act is never silent even if the signal emitter is degraded.
 */
export async function recordLossWriteoff(
  orgId: OrgId,
  input: RecordLossWriteoffInput,
  deps?: LossWriteoffDeps,
): Promise<{ exceptionId: number }> {
  const d = deps ?? (await realDeps());
  const { id } = await d.recordException(orgId, {
    receivingLineId: input.receivingLineId,
    receivingId: input.receivingId ?? null,
    exceptionCode: input.code,
    reason: lossWriteoffReason(input.code, input.deliveredAt ?? null),
    supportNotes: normalizeLossNote(input.note),
    createdBy: input.staffId ?? null,
  });
  return { exceptionId: id };
}

/** Reopen a written-off line — the carton turned up. */
export async function reopenLossWriteoff(
  orgId: OrgId,
  receivingLineId: number,
  staffId: number | null,
  deps?: LossWriteoffDeps,
): Promise<{ resolved: number }> {
  const d = deps ?? (await realDeps());
  let resolved = 0;
  for (const code of LOSS_EXCEPTION_CODES) {
    resolved += await d.resolveExceptions(
      orgId,
      receivingLineId,
      { exceptionCode: code, resolvedBy: staffId },
    );
  }
  return { resolved };
}
