/** Photo-policy gate OVERRIDE — the soft-block half of the receiving photo-evidence gate (WS-PHOTO §4,… */

import type { OrgId } from '@/lib/tenancy/constants';
import { recordReceivingException } from './exceptions';
import {
  PHOTO_POLICY_OVERRIDE_CODES,
  isPhotoPolicyOverrideCode,
  type PhotoPolicyOverrideCode,
} from './exception-codes';
import {
  PHOTO_POLICY_ERROR_CODE,
  PHOTO_POLICY_OVERRIDE_BODY_KEY,
} from './photo-policy-override-wire';

/** The wire tokens now live in the dependency-free `./photo-policy-override-wire` so the BENCH UI can read the same strings without… */
export { PHOTO_POLICY_OVERRIDE_BODY_KEY };

/** 400 discriminator for an override value outside the system vocabulary. */
const PHOTO_POLICY_OVERRIDE_INVALID = 'INVALID_PHOTO_POLICY_OVERRIDE';

type PhotoPolicyOverrideParse =
  /** No override on the request — the gate stays a hard 409. */
  | { state: 'absent' }
  /** A recognized `PHOTO_WAIVED_*` code. */
  | { state: 'valid'; code: PhotoPolicyOverrideCode }
  /** Present but not in the vocabulary — reject the request outright. */
  | { state: 'invalid' };

/** Classify the raw body value. */
export function parsePhotoPolicyOverride(raw: unknown): PhotoPolicyOverrideParse {
  if (raw === undefined || raw === null) return { state: 'absent' };
  if (typeof raw !== 'string') return { state: 'invalid' };
  const trimmed = raw.trim();
  if (trimmed === '') return { state: 'absent' };
  if (!isPhotoPolicyOverrideCode(trimmed)) return { state: 'invalid' };
  return { state: 'valid', code: trimmed };
}

/** 400 body for an override outside the vocabulary — echoes the allowed set. */
export function photoPolicyOverrideInvalidBody(): {
  success: false;
  error: typeof PHOTO_POLICY_OVERRIDE_INVALID;
  allowed: readonly PhotoPolicyOverrideCode[];
} {
  return {
    success: false,
    error: PHOTO_POLICY_OVERRIDE_INVALID,
    allowed: PHOTO_POLICY_OVERRIDE_CODES,
  };
}

interface PhotoPolicyOverrideWarning {
  code: typeof PHOTO_POLICY_ERROR_CODE;
  /** The `PHOTO_WAIVED_*` code the operator selected. */
  reason_code: PhotoPolicyOverrideCode;
  /** The gate blockers that were waived — the same strings the 409 carries. */
  blockers: string[];
}

/**
 * The `warnings[]` entry a waived receive returns at 200. Deliberately mirrors
 * the 409 payload (`code` ≡ `error`, same `blockers`) so a client renders one
 * copy from either shape.
 */
export function photoPolicyOverrideWarning(
  code: PhotoPolicyOverrideCode,
  blockers: readonly string[],
): PhotoPolicyOverrideWarning {
  return { code: PHOTO_POLICY_ERROR_CODE, reason_code: code, blockers: [...blockers] };
}

/** Cap on the server-assembled `reason` text (the column is unbounded `text`). */
const MAX_REASON_LENGTH = 500;

/**
 * Human-readable "what was waived", assembled from the gate's own blockers.
 * Server-generated by construction — the request body never contributes text
 * to this path.
 */
function photoPolicyOverrideReason(blockers: readonly string[]): string {
  const joined = blockers.map((b) => String(b).trim()).filter(Boolean).join('; ');
  const body = joined || 'photo-evidence policy not satisfied';
  const text = `Photo policy waived at receive: ${body}`;
  return text.length > MAX_REASON_LENGTH ? `${text.slice(0, MAX_REASON_LENGTH - 1)}…` : text;
}

interface RecordPhotoPolicyOverrideInput {
  /** REQUIRED — never defaulted; see the module header. */
  code: PhotoPolicyOverrideCode;
  /** The gate verdict's blockers, verbatim. */
  blockers: readonly string[];
  /** Carton the gate scoped evidence to (nullable column on the table). */
  receivingId: number | null;
  /**
   * Every line the receive actually touched. One exception row per line: the
   * table is line-level, the waiver applies to the whole receive act, and
   * `require_one` blockers are carton-level (no single line is "the" culprit).
   */
  receivingLineIds: readonly number[];
  staffId: number | null;
}

interface PhotoPolicyOverrideDeps {
  recordException: typeof recordReceivingException;
}

const defaultDeps: PhotoPolicyOverrideDeps = { recordException: recordReceivingException };

/** Positive, whole, de-duplicated line ids in first-seen order. */
function normalizeLineIds(ids: readonly number[]): number[] {
  const out: number[] = [];
  const seen = new Set<number>();
  for (const raw of ids) {
    const n = Number(raw);
    if (!Number.isFinite(n) || n <= 0) continue;
    const id = Math.floor(n);
    if (seen.has(id)) continue;
    seen.add(id);
    out.push(id);
  }
  return out;
}

/**
 * Persist the override as OPEN `receiving_exceptions` rows. Returns the created
 * ids (empty when there was no resolvable line — the caller still audits, so
 * the act is never silent).
 */
export async function recordPhotoPolicyOverride(
  orgId: OrgId,
  input: RecordPhotoPolicyOverrideInput,
  deps: PhotoPolicyOverrideDeps = defaultDeps,
): Promise<{ exceptionIds: number[] }> {
  const lineIds = normalizeLineIds(input.receivingLineIds);
  if (lineIds.length === 0) return { exceptionIds: [] };

  const reason = photoPolicyOverrideReason(input.blockers);
  const exceptionIds: number[] = [];
  for (const receivingLineId of lineIds) {
    const { id } = await deps.recordException(orgId, {
      receivingLineId,
      receivingId: input.receivingId ?? null,
      exceptionCode: input.code,
      reason,
      createdBy: input.staffId ?? null,
    });
    exceptionIds.push(id);
  }
  return { exceptionIds };
}
