/**
 * Token generator — renders every platform artifact from the registry in
 * `../src` into `../generated/` (committed):
 *
 *   tokens.css          light theme `:root` + every `[data-mode]` block — the
 *                       same declarations app/layout.tsx injects on the web
 *   DesignTokens.swift  `public enum DesignTokens` for iOS (SwiftUI Color)
 *   tokens.json         flat key → value map for design-mcp and tooling
 *
 *   pnpm tokens:build   write the files
 *   pnpm tokens:check   render in memory; exit 1 if any committed file drifts
 *                       (verify gate `Design tokens`)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import {
  INTAKE,
  INBOUND_DELIVERY,
  INBOUND_DELIVERY_STATES,
  INTAKE_CLASSES,
  LIFECYCLE,
  LIFECYCLE_STATES,
  LIGHT_THEME,
  MODE_NAMES,
  MODE_NEUTRAL_REMAP,
  MODE_REGISTRY,
  STATE_NAMES,
  STATE_TONES,
  TRIALS,
  GRAIN_DEPTHS,
  baseColors,
  lightThemeCssText,
  modeRegistryCssText,
  stateCodeCssText,
  trialCssText,
  type ModeSpec,
  type ModeSurfaces,
  type TrialSpec,
} from '../src/index';

const PACKAGE_DIR = path.resolve(__dirname, '..');
const OUT_DIR = path.join(PACKAGE_DIR, 'generated');
const HEADER = 'GENERATED by packages/design-tokens/scripts/generate.ts from packages/design-tokens/src — do not edit. Run `pnpm tokens:build`.';

// ── Resolved mode values (the CSS generator's fallbacks, made concrete) ────

const SURFACE_KEYS = Object.keys(MODE_REGISTRY.triage.surfaces) as (keyof ModeSurfaces)[];

function resolveMode(spec: ModeSpec) {
  const hitCta = spec.hitCta ?? spec.hit;
  return {
    surfaces: spec.surfaces,
    // Light scheme: the mode literal, else the theme's warning text.
    warnText: spec.warnText ?? LIGHT_THEME.vars['text-warning'],
    brand: spec.brand,
    grain: spec.grain,
    radius: spec.radius,
    radiusPill: spec.radiusPill,
    pagePad: spec.pagePad,
    hit: spec.hit,
    hitCta,
    bodyText: spec.bodyText,
    motion: {
      feedback: spec.motion.feedback,
      press: spec.motion.press ?? spec.motion.feedback,
      pulse: spec.motion.pulse ?? '0s',
    },
  };
}

function renderCss(): string {
  return `/* ${HEADER} */\n\n${lightThemeCssText()}\n\n${modeRegistryCssText()}\n\n${stateCodeCssText()}\n\n${trialCssText()}\n`;
}

// ── tokens.json ─────────────────────────────────────────────────────────────

function renderJson(): string {
  const flat: Record<string, string> = {};
  for (const [family, scale] of Object.entries(baseColors)) {
    if (typeof scale === 'string') flat[`primitive.${family}`] = scale;
    else for (const [step, hex] of Object.entries(scale)) flat[`primitive.${family}.${step}`] = hex;
  }
  for (const name of STATE_NAMES) {
    for (const [role, hex] of Object.entries(STATE_TONES[name])) flat[`state.${name}.${role}`] = hex;
  }
  for (const state of LIFECYCLE_STATES) {
    for (const [field, value] of Object.entries(LIFECYCLE[state])) flat[`lifecycle.${state}.${field}`] = value;
  }
  for (const state of INBOUND_DELIVERY_STATES) {
    for (const [field, value] of Object.entries(INBOUND_DELIVERY[state])) {
      flat[`inboundDelivery.${state}.${field}`] = String(value);
    }
  }
  for (const cls of INTAKE_CLASSES) {
    for (const [field, value] of Object.entries(INTAKE[cls])) flat[`intake.${cls}.${field}`] = value;
  }
  for (const [key, value] of Object.entries(LIGHT_THEME.vars)) flat[`theme.light.${key}`] = value;
  flat['theme.light.page.background'] = LIGHT_THEME.page.background;
  flat['theme.light.page.foreground'] = LIGHT_THEME.page.foreground;
  for (const name of MODE_NAMES) {
    const m = resolveMode(MODE_REGISTRY[name]);
    const p = `mode.${name}`;
    for (const key of SURFACE_KEYS) flat[`${p}.surface.${key}`] = m.surfaces[key];
    flat[`${p}.warnText`] = m.warnText;
    if (m.brand) flat[`${p}.brand`] = m.brand;
    if (m.grain) {
      for (const depth of GRAIN_DEPTHS) {
        flat[`${p}.grain.${depth}.opacity`] = String(m.grain[depth].opacity);
        flat[`${p}.grain.${depth}.frequency`] = String(m.grain[depth].frequency);
      }
    }
    flat[`${p}.radius`] = m.radius;
    flat[`${p}.radiusPill`] = m.radiusPill;
    for (const [measure, value] of Object.entries({
      pagePad: m.pagePad,
      hit: m.hit,
      hitCta: m.hitCta,
      bodyText: m.bodyText,
    })) {
      flat[`${p}.${measure}.base`] = value.base;
      flat[`${p}.${measure}.coarse`] = value.coarse;
    }
    for (const [motion, value] of Object.entries(m.motion)) flat[`${p}.motion.${motion}`] = value;
  }
  for (const [themeKey, surface] of Object.entries(MODE_NEUTRAL_REMAP)) {
    flat[`modeNeutralRemap.${themeKey}`] = surface;
  }
  for (const [trial, spec] of Object.entries(TRIALS) as [string, TrialSpec][]) {
    for (const [mode, values] of Object.entries(spec.modes ?? {})) {
      for (const [key, value] of Object.entries(values)) flat[`trial.${trial}.mode.${mode}.${key}`] = value;
    }
    for (const [key, value] of Object.entries(spec.components ?? {})) flat[`trial.${trial}.component.${key}`] = value;
  }
  return `${JSON.stringify({ $comment: HEADER, tokens: flat }, null, 2)}\n`;
}

// ── DesignTokens.swift ──────────────────────────────────────────────────────

function swiftColor(hex: string): string {
  const m = /^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex);
  if (!m) throw new Error(`DesignTokens.swift: '${hex}' is not a #rrggbb colour`);
  const [r, g, b] = m.slice(1).map((h) => parseInt(h, 16));
  return `Color(red: ${r}.0 / 255.0, green: ${g}.0 / 255.0, blue: ${b}.0 / 255.0)`;
}

/** CSS length → points. Only unitless 0 and px exist in the registry. */
function swiftLength(css: string): string {
  const m = /^(\d+(?:\.\d+)?)(px)?$/.exec(css);
  if (!m || (!m[2] && m[1] !== '0')) throw new Error(`DesignTokens.swift: '${css}' is not a px length`);
  return m[1].includes('.') ? m[1] : `${m[1]}.0`;
}

/** CSS time → seconds. */
function swiftSeconds(css: string): string {
  const m = /^(\d+(?:\.\d+)?)(ms|s)$/.exec(css);
  if (!m) throw new Error(`DesignTokens.swift: '${css}' is not a CSS time`);
  const seconds = m[2] === 'ms' ? Number(m[1]) / 1000 : Number(m[1]);
  return Number.isInteger(seconds) ? `${seconds}.0` : String(seconds);
}

const I1 = '    ';
const I2 = I1 + I1;
const I3 = I2 + I1;

function renderSwift(): string {
  const out: string[] = [
    `// ${HEADER}`,
    '//',
    '// Cross-platform design tokens: the same values the web and desktop read as',
    '// CSS custom properties. Light scheme only (the floor apps are light-only).',
    '',
    'import CoreGraphics',
    'import SwiftUI',
    '',
    'public enum DesignTokens {',
    `${I1}/// A task mode's light palette, geometry and motion. Lengths are points;`,
    `${I1}/// \`…Touch\` is the coarse-pointer (touch) value; durations are seconds.`,
    `${I1}public struct Mode: Sendable {`,
  ];
  const surfaceDocs: Record<keyof ModeSurfaces, string> = {
    canvas: 'Page plane.',
    bar: 'Bar / header band.',
    panel: 'Panel / row plane.',
    well: 'Sunken well.',
    hover: 'Row / interaction wash.',
    ink: 'Primary ink.',
    muted: 'Secondary text.',
    faint: 'Faint text — the lightest text a mode allows.',
    rule: 'Inner dividers.',
    edge: 'Edge / hairline around a surface.',
    control: 'Border of an input / control.',
  };
  const fields: [string, string, string][] = [
    ...SURFACE_KEYS.map((k): [string, string, string] => [k, 'Color', surfaceDocs[k]]),
    ['warnText', 'Color', 'Warning ink as text.'],
    ['brand', 'Color?', 'Default tenant brand colour, when the mode has one.'],
    ['radius', 'CGFloat', 'Corner radius.'],
    ['radiusPill', 'CGFloat', 'Pill corner radius.'],
    ['pagePad', 'CGFloat', 'Page padding (pointer).'],
    ['pagePadTouch', 'CGFloat', 'Page padding (touch).'],
    ['hitMin', 'CGFloat', 'Minimum hit target (pointer).'],
    ['hitMinTouch', 'CGFloat', 'Minimum hit target (touch).'],
    ['hitCta', 'CGFloat', 'Primary-action hit target (pointer).'],
    ['hitCtaTouch', 'CGFloat', 'Primary-action hit target (touch).'],
    ['bodyText', 'CGFloat', 'Body text size (pointer).'],
    ['bodyTextTouch', 'CGFloat', 'Body text size (touch).'],
    ['motionFeedback', 'Double', 'State-change feedback duration.'],
    ['motionPress', 'Double', 'Press response duration.'],
    ['motionPulse', 'Double', 'Indeterminate pulse period (0 = none).'],
  ];
  for (const [name, type, doc] of fields) {
    out.push(`${I2}/// ${doc}`, `${I2}public let ${name}: ${type}`);
  }
  for (const name of MODE_NAMES) {
    const m = resolveMode(MODE_REGISTRY[name]);
    const values: Record<string, string> = {};
    for (const key of SURFACE_KEYS) values[key] = `${swiftColor(m.surfaces[key])}, // ${m.surfaces[key]}`;
    values.warnText = `${swiftColor(m.warnText)}, // ${m.warnText}`;
    values.brand = m.brand ? `${swiftColor(m.brand)}, // ${m.brand}` : 'nil,';
    values.radius = `${swiftLength(m.radius)},`;
    values.radiusPill = `${swiftLength(m.radiusPill)},`;
    values.pagePad = `${swiftLength(m.pagePad.base)},`;
    values.pagePadTouch = `${swiftLength(m.pagePad.coarse)},`;
    values.hitMin = `${swiftLength(m.hit.base)},`;
    values.hitMinTouch = `${swiftLength(m.hit.coarse)},`;
    values.hitCta = `${swiftLength(m.hitCta.base)},`;
    values.hitCtaTouch = `${swiftLength(m.hitCta.coarse)},`;
    values.bodyText = `${swiftLength(m.bodyText.base)},`;
    values.bodyTextTouch = `${swiftLength(m.bodyText.coarse)},`;
    values.motionFeedback = `${swiftSeconds(m.motion.feedback)},`;
    values.motionPress = `${swiftSeconds(m.motion.press)},`;
    values.motionPulse = `${swiftSeconds(m.motion.pulse)}`;
    out.push('', `${I2}/// ${MODE_REGISTRY[name].label}: ${MODE_REGISTRY[name].hint}`);
    out.push(`${I2}public static let ${name} = Mode(`);
    for (const [field] of fields) out.push(`${I3}${field}: ${values[field]}`);
    out.push(`${I2})`);
  }
  out.push(
    `${I1}}`,
    '',
    `${I1}/// One state colour: text ink, solid fill, pastel tint, tint border, and`,
    `${I1}/// the solid badge behind a lifecycle code with the ink printed on it.`,
    `${I1}public struct Tone: Sendable {`,
    `${I2}public let text: Color`,
    `${I2}public let fill: Color`,
    `${I2}public let tint: Color`,
    `${I2}public let edge: Color`,
    `${I2}public let code: Color`,
    `${I2}public let codeInk: Color`,
    `${I1}}`,
    '',
    `${I1}/// State colours — what a thing IS; mode- and platform-independent.`,
    `${I1}/// Shipped is \`success\`, never \`fulfillment\`.`,
    `${I1}public enum State {`,
  );
  STATE_NAMES.forEach((name, i) => {
    const tone = STATE_TONES[name];
    if (i > 0) out.push('');
    out.push(`${I2}public static let ${name} = Tone(`);
    const roles = Object.entries(tone);
    roles.forEach(([role, hex], j) => {
      out.push(`${I3}${role}: ${swiftColor(hex)}${j < roles.length - 1 ? ',' : ''} // ${hex}`);
    });
    out.push(`${I2})`);
  });
  out.push(
    `${I1}}`,
    '',
    `${I1}/// One lifecycle state: 3-letter mono code, full word (what the code reads`,
    `${I1}/// as), its state colour, and the Lucide icon name drawn before the code`,
    `${I1}/// (map it to the nearest SF Symbol).`,
    `${I1}public struct LifecycleState: Sendable {`,
    `${I2}public let code: String`,
    `${I2}public let label: String`,
    `${I2}public let tone: Tone`,
    `${I2}public let icon: String`,
    `${I1}}`,
    '',
    `${I1}/// Lifecycle states — one meaning, code and colour on every platform.`,
    `${I1}/// Packed is \`fulfillment\`; shipped is \`success\`.`,
    `${I1}public enum Lifecycle {`,
  );
  for (const state of LIFECYCLE_STATES) {
    const { code, label, tone, icon } = LIFECYCLE[state];
    out.push(
      `${I2}public static let ${state} = LifecycleState(code: ${JSON.stringify(code)}, label: ${JSON.stringify(label)}, tone: State.${tone}, icon: ${JSON.stringify(icon)})`,
    );
  }
  out.push(
    `${I1}}`,
    '',
    `${I1}/// Carrier-facing inbound states — never aliases of outbound lifecycle.`,
    `${I1}public enum InboundDelivery {`,
  );
  for (const state of INBOUND_DELIVERY_STATES) {
    const { code, label, tone, icon } = INBOUND_DELIVERY[state];
    out.push(
      `${I2}public static let ${swiftIdent(state.toLowerCase())} = LifecycleState(code: ${JSON.stringify(code)}, label: ${JSON.stringify(label)}, tone: State.${tone}, icon: ${JSON.stringify(icon)})`,
    );
  }
  out.push(
    `${I1}}`,
    '',
    `${I1}/// One intake class: 3-letter mono code and the full word it reads as.`,
    `${I1}/// A category, not a state — neutral ink; colour only from the scan outcome.`,
    `${I1}public struct IntakeClass: Sendable {`,
    `${I2}public let code: String`,
    `${I2}public let label: String`,
    `${I1}}`,
    '',
    `${I1}/// Intake classes — what an arrived package is (arrival triage).`,
    `${I1}public enum Intake {`,
  );
  for (const cls of INTAKE_CLASSES) {
    const { code, label } = INTAKE[cls];
    out.push(`${I2}public static let ${swiftIdent(cls)} = IntakeClass(code: ${JSON.stringify(code)}, label: ${JSON.stringify(label)})`);
  }
  out.push(`${I1}}`, '}', '');
  return out.join('\n');
}

/** Swift keywords a registry key may collide with (`return` is an intake class). */
const SWIFT_KEYWORDS: Record<string, true> = Object.fromEntries(
  ['return', 'repeat', 'default', 'case', 'in', 'is', 'as', 'do', 'if', 'for', 'while', 'switch', 'where', 'class', 'struct', 'enum', 'protocol', 'let', 'var', 'func', 'import', 'static', 'self', 'Self', 'true', 'false', 'nil', 'throw', 'try', 'catch', 'defer', 'guard', 'else', 'break', 'continue', 'fallthrough', 'internal', 'private', 'public', 'operator', 'init', 'deinit', 'extension', 'subscript', 'typealias', 'associatedtype', 'inout', 'super', 'rethrows', 'throws', 'Any'].map((k) => [k, true as const]),
);

/** A registry key as a Swift identifier — backticked when it is a keyword. */
function swiftIdent(name: string): string {
  return SWIFT_KEYWORDS[name] ? `\`${name}\`` : name;
}

// ── Main ────────────────────────────────────────────────────────────────────

const FILES: Record<string, () => string> = {
  'tokens.css': renderCss,
  'DesignTokens.swift': renderSwift,
  'tokens.json': renderJson,
};

const check = process.argv.includes('--check');
const drifted: string[] = [];
for (const [file, render] of Object.entries(FILES)) {
  const target = path.join(OUT_DIR, file);
  const next = render();
  if (check) {
    let current: string | null = null;
    try {
      current = readFileSync(target, 'utf8');
    } catch {
      /* missing counts as drift */
    }
    if (current !== next) drifted.push(path.relative(process.cwd(), target));
  } else {
    writeFileSync(target, next);
    console.log(`wrote ${path.relative(process.cwd(), target)}`);
  }
}

if (drifted.length > 0) {
  console.error(
    `✗ design tokens: generated file(s) drifted from packages/design-tokens/src:\n  ${drifted.join('\n  ')}\n  Run \`pnpm tokens:build\` and commit the result.`,
  );
  process.exit(1);
}
if (check) console.log(`✓ design tokens: ${Object.keys(FILES).length} generated files match the source`);
