'use client';
import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Check } from '@/components/Icons';
import { Button, EmptyState, Inset, TextField } from '@/design-system/primitives';

type Line = { id: number; fnsku: string; display_title?: string | null; status: string };
type Plan = { id: number; shipment_ref: string; items: Line[] } | null;

/** Binds every packed line in the current plan to one label through the canonical label write. */
export function MobileFbaLabelBindTask() {
  const [plan, setPlan] = useState<Plan>(null); const [label, setLabel] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const r = await fetch('/api/fba/shipments/today', { cache: 'no-store' }); const d = await r.json().catch(() => ({})); if (!r.ok || d?.success === false) throw new Error(d?.error || 'Could not load today’s FBA plan.'); setPlan(d?.shipment ?? null); } catch (c) { setError(c instanceof Error ? c.message : 'Could not load today’s FBA plan.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const packed = plan?.items.filter((line) => line.status === 'PACKED') ?? [];
  const bind = async () => { const barcode = label.trim(); if (!barcode) { setError('Enter the shipping label barcode.'); return; } if (!plan || packed.length === 0) return; setSaving(true); setError(null); try { const r = await fetch('/api/fba/labels/bind', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ shipment_id: plan.id, label_barcode: barcode, fnskus: packed.map((line) => line.fnsku), station: 'MOBILE_FBA' }) }); const d = await r.json().catch(() => ({})); if (!r.ok || d?.success === false) throw new Error(d?.error || 'Could not bind the label.'); setLabel(''); setNotice(`${d?.bound_count ?? packed.length} packed line${packed.length === 1 ? '' : 's'} bound.`); await load(); } catch (c) { setError(c instanceof Error ? c.message : 'Could not bind the label.'); } finally { setSaving(false); } };
  return <main className="flex h-full min-h-0 flex-col bg-surface-card" aria-label="FBA label binding"><header className="border-b border-border-hairline px-3 pb-3 pt-2"><p className="text-role-eyebrow uppercase tracking-[0.14em] text-text-soft">Amazon prep</p><h1 className="mt-1 text-lg font-semibold tracking-tight text-text-default">Bind shipping label</h1><p className="mt-0.5 text-role-caption text-text-muted">Bind all packed lines in today’s plan to the label in hand. Camera capture stays in the shell.</p></header><Inset space="chip" className="border-b border-border-hairline"><div className="grid grid-cols-[minmax(0,1fr)_auto] border border-border-soft bg-border-soft"><TextField label="Label barcode" value={label} onChange={setLabel} appearance="flush" mono disabled={saving} /><Button type="button" variant="primary" radius="flush" size="md" onClick={() => void bind()} disabled={saving || packed.length === 0}>Bind</Button></div>{notice ? <p className="mt-2 text-role-caption font-semibold text-text-success">{notice}</p> : null}</Inset><div className="min-h-0 flex-1 overflow-y-auto">{error ? <p className="border-b border-border-hairline px-3 py-4 text-role-caption font-semibold text-text-danger"><AlertTriangle className="mr-2 inline h-4 w-4" />{error}</p> : null}{!loading && packed.length === 0 ? <EmptyState icon={<Check className="h-6 w-6 text-text-soft" />} title="No packed FBA lines" description="Packed plan lines appear here when they are ready to bind to a shipping label." /> : <ul className="divide-y divide-border-hairline">{packed.map((line) => <li key={line.id} className="px-3 py-3"><p className="font-mono text-role-caption font-semibold text-text-default">{line.fnsku}</p><p className="text-role-micro text-text-soft">{line.display_title || 'No catalog title'}</p></li>)}</ul>}</div></main>;
}
