'use client';
import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Check } from '@/components/Icons';
import { Button, EmptyState } from '@/design-system/primitives';

type Plan = { id: number; shipment_ref: string; items: { id: number; status: string }[] } | null;
/** Irreversible FBA close: explicit confirmation, standard safety checks, no force path. */
export function MobileFbaCloseTask() {
  const [plan, setPlan] = useState<Plan>(null); const [confirmed, setConfirmed] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [done, setDone] = useState<number | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const r = await fetch('/api/fba/shipments/today', { cache: 'no-store' }); const d = await r.json().catch(() => ({})); if (!r.ok || d?.success === false) throw new Error(d?.error || 'Could not load today’s FBA plan.'); setPlan(d?.shipment ?? null); } catch (c) { setError(c instanceof Error ? c.message : 'Could not load today’s FBA plan.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const close = async () => { if (!plan || !confirmed) return; setSaving(true); setError(null); try { const r = await fetch('/api/fba/shipments/close', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ shipment_id: plan.id, force: false, station: 'MOBILE_FBA' }) }); const d = await r.json().catch(() => ({})); if (!r.ok || d?.success === false) throw new Error(d?.error || 'Could not close this FBA shipment.'); setDone(Number(d?.items_shipped ?? 0)); setPlan(null); } catch (c) { setError(c instanceof Error ? c.message : 'Could not close this FBA shipment.'); } finally { setSaving(false); } };
  return <main className="flex h-full min-h-0 flex-col bg-surface-card" aria-label="Close FBA shipment"><header className="border-b border-border-hairline px-3 pb-3 pt-2"><p className="text-role-eyebrow uppercase tracking-[0.14em] text-text-soft">Amazon prep</p><h1 className="mt-1 text-lg font-semibold tracking-tight text-text-default">Close and send</h1><p className="mt-0.5 text-role-caption text-text-muted">This records shipment completion and cannot be undone. Standard planned-line checks remain active.</p></header><div className="min-h-0 flex-1 overflow-y-auto">{error ? <p className="border-b border-border-hairline px-3 py-4 text-role-caption font-semibold text-text-danger"><AlertTriangle className="mr-2 inline h-4 w-4" />{error}</p> : null}{done !== null ? <section className="border-b border-border-success bg-surface-success px-3 py-4"><p className="flex items-center gap-2 text-role-caption font-semibold text-text-success"><Check className="h-4 w-4" /> Shipment closed</p><p className="mt-2 text-role-caption text-text-default">{done} item{done === 1 ? '' : 's'} marked shipped.</p></section> : null}{!loading && !plan && done === null ? <EmptyState icon={<Check className="h-6 w-6 text-text-soft" />} title="No open FBA plan" description="An open plan appears here when it is ready for final close and send." /> : plan ? <section className="px-3 py-4"><p className="font-mono text-role-caption font-semibold text-text-default">{plan.shipment_ref}</p><p className="mt-1 text-role-caption text-text-muted">{plan.items.length} plan lines. The server will refuse close while any line remains planned.</p><label className="mt-4 flex min-h-11 items-center gap-2 border border-border-soft bg-surface-card px-3 text-role-field font-semibold text-text-default"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /> I confirm this shipment has left the facility.</label><Button className="mt-3 w-full" type="button" variant="primary" radius="flush" size="md" onClick={() => void close()} disabled={!confirmed || saving}>Close shipment</Button></section> : null}</div></main>;
}
