'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  BINS_GRID_COLUMNS,
  BINS_GRID_FROZEN_CELL,
  binsGridCell,
  binsGridFrozenLeft,
  binsGridRowShellClass,
  binsGridTemplate,
  isBinsGridFrozen,
  isBinsGridSortable,
  type BinsGridColumn,
  type BinsGridColumnKey,
} from './bins-grid-layout';

const BINS_HEADER_LAYOUT: LedgerHeaderLayoutApi<BinsGridColumn> = {
  template: binsGridTemplate,
  cellClass: binsGridCell,
  rowShellClass: binsGridRowShellClass,
  frozenCellClass: BINS_GRID_FROZEN_CELL,
  frozenLeft: (key) => binsGridFrozenLeft(key as BinsGridColumnKey),
  isFrozen: isBinsGridFrozen,
  isSortable: isBinsGridSortable,
  // Identity track is `barcode`, not the house-default `title`.
  frozenEdgeKey: 'barcode',
};

/**
 * Sticky column header for the bins LedgerGrid. Bins are always multi-select, so
 * `selectMode: 'always'` makes `selectionScope` a REQUIRED prop — select-all
 * without a scope would render a checkbox that does nothing.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const BinsGridColumnHeader = makeLedgerGridColumnHeader<
  BinsGridColumn,
  BinsGridColumnKey,
  'always'
>({
  layout: BINS_HEADER_LAYOUT,
  defaultColumns: BINS_GRID_COLUMNS,
  selectMode: 'always',
  tableId: 'bins',
});
