'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  BINS_GRID_COLUMNS,
  isBinsGridSortable,
  type BinsGridColumn,
  type BinsGridColumnKey,
} from './bins-grid-layout';

/**
 * The per-family layout fields this carried were aliases of the same shared
 * functions; `LedgerHeaderLayoutApi` collapsed them. What stays per family is
 * which columns sort and where the frozen edge sits.
 */
const BINS_HEADER_LAYOUT: LedgerHeaderLayoutApi = {
  isSortable: isBinsGridSortable,
  frozenEdgeKey: 'barcode',
};

/**
 * Sticky column header for the bins LedgerGrid. Bins are always multi-select, so
 * `selectMode: 'always'` makes `selectionScope` a REQUIRED prop — select-all
 * without a scope would render a checkbox that does nothing.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const BinsGridColumnHeader = makeLedgerGridColumnHeader<
  BinsGridColumn,
  BinsGridColumnKey,
  'always'
>({
  layout: BINS_HEADER_LAYOUT,
  defaultColumns: BINS_GRID_COLUMNS,
  selectMode: 'always',
  tableId: 'bins',
});
