/**
 * Reskin application — the runtime half of the QA Design Lab's cherry-pick
 * toggle. Pure + framework-agnostic so the boot script, the HUD and any deep
 * link share one source of truth, exactly like src/lib/theme/theme.ts.
 *
 * The SELECTION (a list of group ids) lives on <html> as `data-reskin`; the CSS
 * that reads it is generated by src/design-system/themes/reskin.ts, one block
 * per group per scheme, matched with the `~=` attribute operator. An empty
 * selection removes the attribute, so a lab session that has never flipped a
 * group renders byte-identical to dogfood.
 *
 * Storage is sessionStorage, not localStorage: a reskin preview is a QA
 * sitting, not a preference. Closing the tab ends it.
 *
 * Precedence: `?reskin=` on the URL wins over storage, so a catalog deep link
 * and the split-compare iframes are self-describing. The query value is only
 * PERSISTED from a top-level document — a split-compare iframe must not write
 * its side back into the tab's storage (same-origin frames share it).
 *
 * The wire format accepts a space-, comma- or plus-separated list plus the
 * `after` alias for "every group", so `?reskin=after` deep links written before
 * groups existed still resolve. The attribute is always written canonically
 * (RESKIN_GROUP_IDS order), so two equivalent selections stamp identical markup.
 */

import {
  RESKIN_ALL_ALIAS,
  RESKIN_ATTR,
  RESKIN_GROUP_IDS,
  isEveryGroup,
  parseReskinSelection,
  serializeReskinSelection,
  type ReskinGroupId,
} from '@/design-system/themes/reskin';

export const RESKIN_STORAGE_KEY = 'ds-reskin';
export const RESKIN_QUERY_PARAM = 'reskin';

type SelectionInput = string | readonly ReskinGroupId[] | null | undefined;

function toSelection(input: SelectionInput): ReskinGroupId[] {
  if (Array.isArray(input)) return parseReskinSelection(input.join(' '));
  return parseReskinSelection(typeof input === 'string' ? input : null);
}

/**
 * The shortest value that round-trips a selection. "Everything" writes the
 * `after` alias rather than nine ids, so a URL a human has to read or paste
 * stays short and a full selection is recognisable at a glance.
 */
export function reskinWireValue(ids: readonly ReskinGroupId[]): string {
  if (ids.length === 0) return '';
  return isEveryGroup(ids) ? RESKIN_ALL_ALIAS : serializeReskinSelection(ids);
}

/**
 * Stamp a selection on <html> and cache it. An empty selection clears the
 * attribute AND the storage key — "before" is the absence of both.
 *
 * The ATTRIBUTE always carries the expanded id list (never the alias): the CSS
 * matches with `~=` on group ids, so `data-reskin="after"` would select nothing.
 */
export function applyReskin(input: SelectionInput): ReskinGroupId[] {
  const next = toSelection(input);
  if (typeof document === 'undefined') return next;

  const el = document.documentElement;
  const attr = serializeReskinSelection(next);
  if (attr === '') el.removeAttribute(RESKIN_ATTR);
  else el.setAttribute(RESKIN_ATTR, attr);

  try {
    const wire = reskinWireValue(next);
    if (wire === '') sessionStorage.removeItem(RESKIN_STORAGE_KEY);
    else sessionStorage.setItem(RESKIN_STORAGE_KEY, wire);
  } catch {
    /* private mode / storage disabled — the attribute is still applied */
  }
  return next;
}

/** Toggle one group, leaving the rest of the selection alone. */
export function toggleReskinGroup(
  current: readonly ReskinGroupId[],
  group: ReskinGroupId,
): ReskinGroupId[] {
  const next = current.includes(group)
    ? current.filter((id) => id !== group)
    : [...current, group];
  return parseReskinSelection(next.join(' '));
}

/** What is on <html> right now (not what is stored). */
export function readAppliedReskin(): ReskinGroupId[] {
  if (typeof document === 'undefined') return [];
  return parseReskinSelection(document.documentElement.getAttribute(RESKIN_ATTR));
}

/** Query wins, then storage, then empty. */
export function readReskinPreference(search?: string): ReskinGroupId[] {
  if (typeof window === 'undefined') return [];
  const raw = search ?? window.location.search;
  try {
    const fromQuery = new URLSearchParams(raw).get(RESKIN_QUERY_PARAM);
    if (fromQuery !== null) return parseReskinSelection(fromQuery);
  } catch {
    /* malformed query — fall through to storage */
  }
  try {
    return parseReskinSelection(sessionStorage.getItem(RESKIN_STORAGE_KEY));
  } catch {
    return [];
  }
}

/** Append/replace `?reskin=` on a href. An empty selection drops the param. */
export function withReskinParam(href: string, input: SelectionInput): string {
  const ids = toSelection(input);
  const [path, hash = ''] = href.split('#');
  const [base, query = ''] = path.split('?');
  const params = new URLSearchParams(query);
  const wire = reskinWireValue(ids);
  if (wire === '') params.delete(RESKIN_QUERY_PARAM);
  else params.set(RESKIN_QUERY_PARAM, wire);
  const nextQuery = params.toString();
  return `${base}${nextQuery ? `?${nextQuery}` : ''}${hash ? `#${hash}` : ''}`;
}

/**
 * Inline boot script (runs in <head> before first paint) so a lab deep link or
 * a restored sitting never flashes the un-reskinned tokens. Kept tiny and
 * dependency-free; the valid id list is inlined from the registry at build
 * time. Only emitted for a Design-Lab-entitled session (see app/layout.tsx).
 *
 * It re-implements `parseReskinSelection` in ~5 lines rather than importing it:
 * this string runs before any bundle, so it cannot share the module — the
 * canonical-order filter is duplicated deliberately and the tripwire in
 * catalog.test.ts asserts the two agree on the id list.
 */
export const RESKIN_BOOT_SCRIPT =
  `(function(){try{var G=${JSON.stringify(RESKIN_GROUP_IDS)};` +
  `var q=null;try{q=new URLSearchParams(location.search).get('${RESKIN_QUERY_PARAM}');}catch(e){}` +
  // A same-origin split-compare frame reads its side off the URL but must never
  // write it back — sessionStorage is shared with the hosting tab.
  `var top=false;try{top=window.top===window.self;}catch(e){}` +
  `var v=q;` +
  `if(v!==null&&top){try{sessionStorage.setItem('${RESKIN_STORAGE_KEY}',v);}catch(e){}}` +
  `if(v===null){try{v=sessionStorage.getItem('${RESKIN_STORAGE_KEY}');}catch(e){}}` +
  `if(!v){return;}` +
  `var t=String(v).split(/[\\s,+]+/).filter(Boolean);` +
  `var all=t.indexOf('${RESKIN_ALL_ALIAS}')>-1;` +
  `var sel=G.filter(function(g){return all||t.indexOf(g)>-1;});` +
  `if(sel.length){document.documentElement.setAttribute('${RESKIN_ATTR}',sel.join(' '));}` +
  `}catch(e){}})();`;

export {
  RESKIN_ALL_ALIAS,
  RESKIN_ATTR,
  RESKIN_GROUP_IDS,
  isEveryGroup,
  parseReskinSelection,
  serializeReskinSelection,
  type ReskinGroupId,
};
