/**
 * Workbench sticky headers (except Orders — permanent allowlisted fork)
 * must be generated by {@link makeLedgerGridColumnHeader} — never re-fork the
 * select-all / sort / frozen / tip recipe, and never re-hand-roll the prop
 * forwarding the factory exists to own.
 *
 * **This guard DISCOVERS its scope off disk.** It used to hand-list ten
 * adapters, and by the time the factory landed the tree held twelve — `My Day`
 * and both `Review · Catalog link` headers had never been guarded at all,
 * exactly the "hand-listed scope" gap the capabilities guard closed for mounts.
 * A list can only certify what someone remembered to add to it.
 */
import assert from 'node:assert/strict';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../..');
const SRC = path.join(ROOT, 'src');

/**
 * The DS modules themselves — they DEFINE the recipe rather than composing it.
 * `OrdersQueueColumnHeader` is deliberately outside the walk (it is not named
 * `*GridColumnHeader.tsx`): Orders is the **permanent** allowlisted header fork
 * (drag-reorder + viewport force-hide). Do not half-port onto the factory —
 * see `source-of-truth.md` → Sticky LedgerGrid column-header row.
 */
const DS_OWN = new Set([
  'src/design-system/components/grid/LedgerGridColumnHeader.tsx',
  'src/design-system/components/grid/makeLedgerGridColumnHeader.tsx',
]);

function walkAdapters(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules' || entry.startsWith('.')) continue;
    const abs = path.join(dir, entry);
    if (statSync(abs).isDirectory()) {
      walkAdapters(abs, out);
    } else if (entry.endsWith('GridColumnHeader.tsx')) {
      const rel = path.relative(ROOT, abs);
      if (!DS_OWN.has(rel)) out.push(rel);
    }
  }
  return out;
}

const ADAPTERS = walkAdapters(SRC).sort();

describe('LedgerGridColumnHeader composition', () => {
  it('the walk actually finds the family adapters', () => {
    // A discovery guard that discovers nothing is green and worthless.
    assert.ok(
      ADAPTERS.length >= 10,
      `expected the grid families' header adapters, found ${ADAPTERS.length}`,
    );
  });

  for (const rel of ADAPTERS) {
    it(`${path.basename(rel)} is generated by makeLedgerGridColumnHeader`, () => {
      const source = readFileSync(path.join(ROOT, rel), 'utf8');

      assert.match(
        source,
        /makeLedgerGridColumnHeader/,
        `${rel} must be generated by makeLedgerGridColumnHeader — the family supplies a\n` +
          `LedgerHeaderLayoutApi + column model, the factory owns the prop plumbing.\n` +
          `Hand-forwarding activeSort/sortDir/onSortColumn/onOpenColumnDetails is the\n` +
          `~65-line copy-paste the factory replaced.`,
      );

      assert.doesNotMatch(
        source,
        /role="columnheader"/,
        `${rel} must not re-assert columnheader roles — that lives in LedgerGridColumnHeader`,
      );

      // The factory owns select-all; an adapter reaching for the selection bus
      // itself is rebuilding the half the DS header already does.
      assert.doesNotMatch(
        source,
        /emitToggleAll|useTableSelectionTotal/,
        `${rel} must not re-implement select-all — LedgerGridColumnHeader owns it`,
      );
    });
  }
});
