'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  MY_DAY_GRID_COLUMNS,
  isMyDayGridSortable,
  type MyDayGridColumn,
  type MyDayGridColumnKey,
} from '@/lib/my-day/my-day-grid-layout';

/**
 * The per-family layout fields this carried were aliases of the same shared
 * functions; `LedgerHeaderLayoutApi` collapsed them. What stays per family is
 * which columns sort and where the frozen edge sits.
 */
const MY_DAY_HEADER_LAYOUT: LedgerHeaderLayoutApi = {
  isSortable: isMyDayGridSortable,
};

/**
 * Sticky column header for the Today LedgerGrid. Today declares
 * `multiSelect: false`, so the select gutter is a spacer.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const MyDayGridColumnHeader = makeLedgerGridColumnHeader<
  MyDayGridColumn,
  MyDayGridColumnKey
>({
  layout: MY_DAY_HEADER_LAYOUT,
  defaultColumns: MY_DAY_GRID_COLUMNS,
  tableId: 'my-day',
});
