'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  MY_DAY_GRID_COLUMNS,
  MY_DAY_GRID_FROZEN_CELL,
  isMyDayGridFrozen,
  isMyDayGridSortable,
  myDayGridCell,
  myDayGridFrozenLeft,
  myDayGridRowShellClass,
  myDayGridTemplate,
  type MyDayGridColumn,
  type MyDayGridColumnKey,
} from '@/lib/my-day/my-day-grid-layout';

const MY_DAY_HEADER_LAYOUT: LedgerHeaderLayoutApi<MyDayGridColumn> = {
  template: myDayGridTemplate,
  cellClass: myDayGridCell,
  rowShellClass: myDayGridRowShellClass,
  frozenCellClass: MY_DAY_GRID_FROZEN_CELL,
  frozenLeft: (key) => myDayGridFrozenLeft(key as MyDayGridColumnKey),
  isFrozen: isMyDayGridFrozen,
  isSortable: isMyDayGridSortable,
};

/**
 * Sticky column header for the Today LedgerGrid. Today declares
 * `multiSelect: false`, so the select gutter is a spacer.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const MyDayGridColumnHeader = makeLedgerGridColumnHeader<
  MyDayGridColumn,
  MyDayGridColumnKey
>({ layout: MY_DAY_HEADER_LAYOUT, defaultColumns: MY_DAY_GRID_COLUMNS });
