'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  UNITS_GRID_COLUMNS,
  UNITS_GRID_FROZEN_CELL,
  unitsGridCell,
  unitsGridFrozenLeft,
  unitsGridRowShellClass,
  unitsGridTemplate,
  isUnitsGridFrozen,
  isUnitsGridSortable,
  type UnitsGridColumn,
  type UnitsGridColumnKey,
} from './units-grid-layout';

const UNITS_HEADER_LAYOUT: LedgerHeaderLayoutApi<UnitsGridColumn> = {
  template: unitsGridTemplate,
  cellClass: unitsGridCell,
  rowShellClass: unitsGridRowShellClass,
  frozenCellClass: UNITS_GRID_FROZEN_CELL,
  frozenLeft: (key) => unitsGridFrozenLeft(key as UnitsGridColumnKey),
  isFrozen: isUnitsGridFrozen,
  isSortable: isUnitsGridSortable,
  // Identity track is `serial`, not the house-default `title`.
  frozenEdgeKey: 'serial',
};

/**
 * Sticky column header for the units LedgerGrid. Browse-only —
 * `selectMode: 'never'` (no select-all gutter until bulk unit actions land).
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const UnitsGridColumnHeader = makeLedgerGridColumnHeader<
  UnitsGridColumn,
  UnitsGridColumnKey,
  'never'
>({
  layout: UNITS_HEADER_LAYOUT,
  defaultColumns: UNITS_GRID_COLUMNS,
  selectMode: 'never',
  tableId: 'inventory-units',
});
