'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  UNITS_GRID_COLUMNS,
  isUnitsGridSortable,
  type UnitsGridColumn,
  type UnitsGridColumnKey,
} from './units-grid-layout';

/**
 * The per-family layout fields this carried were aliases of the same shared
 * functions; `LedgerHeaderLayoutApi` collapsed them. What stays per family is
 * which columns sort and where the frozen edge sits.
 */
const UNITS_HEADER_LAYOUT: LedgerHeaderLayoutApi = {
  isSortable: isUnitsGridSortable,
  frozenEdgeKey: 'serial',
};

/**
 * Sticky column header for the units LedgerGrid. Browse-only —
 * `selectMode: 'never'` (no select-all gutter until bulk unit actions land).
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const UnitsGridColumnHeader = makeLedgerGridColumnHeader<
  UnitsGridColumn,
  UnitsGridColumnKey,
  'never'
>({
  layout: UNITS_HEADER_LAYOUT,
  defaultColumns: UNITS_GRID_COLUMNS,
  selectMode: 'never',
  tableId: 'inventory-units',
});
