'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  WARRANTY_GRID_COLUMNS,
  WARRANTY_GRID_FROZEN_CELL,
  isWarrantyGridFrozen,
  isWarrantyGridSortable,
  warrantyGridCell,
  warrantyGridFrozenLeft,
  warrantyGridRowShellClass,
  warrantyGridTemplate,
  type WarrantyGridColumn,
  type WarrantyGridColumnKey,
} from './warranty-grid-layout';

const WARRANTY_HEADER_LAYOUT: LedgerHeaderLayoutApi<WarrantyGridColumn> = {
  template: warrantyGridTemplate,
  cellClass: warrantyGridCell,
  rowShellClass: warrantyGridRowShellClass,
  frozenCellClass: WARRANTY_GRID_FROZEN_CELL,
  frozenLeft: (key) => warrantyGridFrozenLeft(key as WarrantyGridColumnKey),
  isFrozen: isWarrantyGridFrozen,
  isSortable: isWarrantyGridSortable,
};

/**
 * Sticky column header for the warranty LedgerGrid. Read-only browse — the empty
 * `select` gutter keeps the frozen item cell aligned with every house grid.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const WarrantyGridColumnHeader = makeLedgerGridColumnHeader<
  WarrantyGridColumn,
  WarrantyGridColumnKey
>({ layout: WARRANTY_HEADER_LAYOUT, defaultColumns: WARRANTY_GRID_COLUMNS });
