'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  WARRANTY_GRID_COLUMNS,
  isWarrantyGridSortable,
  type WarrantyGridColumn,
  type WarrantyGridColumnKey,
} from './warranty-grid-layout';

/**
 * The per-family layout fields this carried were aliases of the same shared
 * functions; `LedgerHeaderLayoutApi` collapsed them. What stays per family is
 * which columns sort and where the frozen edge sits.
 */
const WARRANTY_HEADER_LAYOUT: LedgerHeaderLayoutApi = {
  isSortable: isWarrantyGridSortable,
};

/**
 * Sticky column header for the warranty LedgerGrid. Read-only browse — the empty
 * `select` gutter keeps the frozen item cell aligned with every house grid.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const WarrantyGridColumnHeader = makeLedgerGridColumnHeader<
  WarrantyGridColumn,
  WarrantyGridColumnKey
>({
  layout: WARRANTY_HEADER_LAYOUT,
  defaultColumns: WARRANTY_GRID_COLUMNS,
  tableId: 'warranty',
});
