export {
  DETAIL_STACK_LAYOUT,
  DETAIL_STACK_RESIZE,
  DETAIL_STACK_COLLAPSE,
  DETAIL_STACK_ASIDE_SURFACE,
  assistantDockAsideClassName,
  assistantDockAsideStyle,
  detailStackAsideClassName,
  detailStackAsideElevatedClassName,
  detailStackAsideStyle,
  detailStackBackdropClassName,
  detailStackBackdropElevatedClassName,
  detailStackCollapseStripClassName,
  detailStackCollapseStripStyle,
  detailStackDismissLayerClassName,
  detailStackDismissLayerElevatedClassName,
} from './layout';