'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  PICKUP_GRID_COLUMNS,
  PICKUP_GRID_FROZEN_CELL,
  isPickupGridFrozen,
  isPickupGridSortable,
  pickupGridCell,
  pickupGridFrozenLeft,
  pickupGridRowShellClass,
  pickupGridTemplate,
  type PickupGridColumn,
  type PickupGridColumnKey,
} from './pickup-grid-layout';

const PICKUP_HEADER_LAYOUT: LedgerHeaderLayoutApi<PickupGridColumn> = {
  template: pickupGridTemplate,
  cellClass: pickupGridCell,
  rowShellClass: pickupGridRowShellClass,
  frozenCellClass: PICKUP_GRID_FROZEN_CELL,
  frozenLeft: (key) => pickupGridFrozenLeft(key as PickupGridColumnKey),
  isFrozen: isPickupGridFrozen,
  isSortable: isPickupGridSortable,
};

/**
 * Sticky column header for the Local Pickup LedgerGrid. Read-only browse — the
 * empty `select` gutter keeps the frozen title aligned with every station grid.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const PickupGridColumnHeader = makeLedgerGridColumnHeader<
  PickupGridColumn,
  PickupGridColumnKey
>({ layout: PICKUP_HEADER_LAYOUT, defaultColumns: PICKUP_GRID_COLUMNS });
