'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  PICKUP_GRID_COLUMNS,
  isPickupGridSortable,
  type PickupGridColumn,
  type PickupGridColumnKey,
} from './pickup-grid-layout';

/**
 * The per-family layout fields this carried were aliases of the same shared
 * functions; `LedgerHeaderLayoutApi` collapsed them. What stays per family is
 * which columns sort and where the frozen edge sits.
 */
const PICKUP_HEADER_LAYOUT: LedgerHeaderLayoutApi = {
  isSortable: isPickupGridSortable,
};

/**
 * Sticky column header for the Local Pickup LedgerGrid. Read-only browse — the
 * empty `select` gutter keeps the frozen title aligned with every station grid.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const PickupGridColumnHeader = makeLedgerGridColumnHeader<
  PickupGridColumn,
  PickupGridColumnKey
>({
  layout: PICKUP_HEADER_LAYOUT,
  defaultColumns: PICKUP_GRID_COLUMNS,
  tableId: 'pickup',
});
