'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  UNFOUND_GRID_COLUMNS,
  UNFOUND_GRID_FROZEN_CELL,
  isUnfoundGridFrozen,
  isUnfoundGridSortable,
  unfoundGridCell,
  unfoundGridFrozenLeft,
  unfoundGridRowShellClass,
  unfoundGridTemplate,
  type UnfoundGridColumn,
  type UnfoundGridColumnKey,
} from './unfound-grid-layout';

const UNFOUND_HEADER_LAYOUT: LedgerHeaderLayoutApi<UnfoundGridColumn> = {
  template: unfoundGridTemplate,
  cellClass: unfoundGridCell,
  rowShellClass: unfoundGridRowShellClass,
  frozenCellClass: UNFOUND_GRID_FROZEN_CELL,
  frozenLeft: (key) => unfoundGridFrozenLeft(key as UnfoundGridColumnKey),
  isFrozen: isUnfoundGridFrozen,
  isSortable: isUnfoundGridSortable,
};

/**
 * Sticky column header for the unfound queue LedgerGrid. No select-all
 * (`multiSelect: false`); the empty `select` gutter keeps the frozen product
 * cell aligned with every house grid.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const UnfoundGridColumnHeader = makeLedgerGridColumnHeader<
  UnfoundGridColumn,
  UnfoundGridColumnKey
>({
  layout: UNFOUND_HEADER_LAYOUT,
  defaultColumns: UNFOUND_GRID_COLUMNS,
  tableId: 'unfound',
});
