'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  UNFOUND_GRID_COLUMNS,
  isUnfoundGridSortable,
  type UnfoundGridColumn,
  type UnfoundGridColumnKey,
} from './unfound-grid-layout';

/**
 * The per-family layout fields this carried were aliases of the same shared
 * functions; `LedgerHeaderLayoutApi` collapsed them. What stays per family is
 * which columns sort and where the frozen edge sits.
 */
const UNFOUND_HEADER_LAYOUT: LedgerHeaderLayoutApi = {
  isSortable: isUnfoundGridSortable,
};

/**
 * Sticky column header for the unfound queue LedgerGrid. No select-all
 * (`multiSelect: false`); the empty `select` gutter keeps the frozen product
 * cell aligned with every house grid.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const UnfoundGridColumnHeader = makeLedgerGridColumnHeader<
  UnfoundGridColumn,
  UnfoundGridColumnKey
>({
  layout: UNFOUND_HEADER_LAYOUT,
  defaultColumns: UNFOUND_GRID_COLUMNS,
  tableId: 'unfound',
});
