'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  CATALOG_GRID_COLUMNS,
  CATALOG_GRID_FROZEN_CELL,
  catalogGridCell,
  catalogGridFrozenLeft,
  catalogGridRowShellClass,
  catalogGridTemplate,
  isCatalogGridFrozen,
  isCatalogGridSortable,
  type CatalogGridColumn,
  type CatalogGridColumnKey,
} from '@/lib/products/catalog-grid-layout';

const CATALOG_HEADER_LAYOUT: LedgerHeaderLayoutApi<CatalogGridColumn> = {
  template: catalogGridTemplate,
  cellClass: catalogGridCell,
  rowShellClass: catalogGridRowShellClass,
  frozenCellClass: CATALOG_GRID_FROZEN_CELL,
  frozenLeft: catalogGridFrozenLeft,
  isFrozen: isCatalogGridFrozen,
  isSortable: isCatalogGridSortable,
};

/**
 * Sticky column header for the catalog LedgerGrid. Catalog multi-select is
 * always-on (same as Repair), so `selectionScope` is required.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const CatalogGridColumnHeader = makeLedgerGridColumnHeader<
  CatalogGridColumn,
  CatalogGridColumnKey,
  'always'
>({ layout: CATALOG_HEADER_LAYOUT, defaultColumns: CATALOG_GRID_COLUMNS, selectMode: 'always' });
