'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  CATALOG_GRID_COLUMNS,
  isCatalogGridSortable,
  type CatalogGridColumn,
  type CatalogGridColumnKey,
} from '@/lib/products/catalog-grid-layout';

/**
 * The per-family layout fields this carried were aliases of the same shared
 * functions; `LedgerHeaderLayoutApi` collapsed them. What stays per family is
 * which columns sort and where the frozen edge sits.
 */
const CATALOG_HEADER_LAYOUT: LedgerHeaderLayoutApi = {
  isSortable: isCatalogGridSortable,
};

/**
 * Sticky column header for the catalog LedgerGrid. Catalog multi-select is
 * always-on (same as Repair), so `selectionScope` is required.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const CatalogGridColumnHeader = makeLedgerGridColumnHeader<
  CatalogGridColumn,
  CatalogGridColumnKey,
  'always'
>({
  layout: CATALOG_HEADER_LAYOUT,
  defaultColumns: CATALOG_GRID_COLUMNS,
  selectMode: 'always',
  tableId: 'catalog',
});
