'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  TRACKING_EXCEPTIONS_GRID_COLUMNS,
  isTrackingExceptionsGridSortable,
  type TrackingExceptionsGridColumn,
  type TrackingExceptionsGridColumnKey,
} from './tracking-exceptions-grid-layout';

/**
 * The per-family layout fields this carried were aliases of the same shared
 * functions; `LedgerHeaderLayoutApi` collapsed them. What stays per family is
 * which columns sort and where the frozen edge sits.
 */
const TRACKING_EXCEPTIONS_HEADER_LAYOUT: LedgerHeaderLayoutApi = {
  isSortable: isTrackingExceptionsGridSortable,
};

/**
 * Sticky column header for the Tracking Exceptions LedgerGrid. Read-only browse —
 * the empty `select` gutter keeps the frozen tracking cell aligned.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const TrackingExceptionsGridColumnHeader = makeLedgerGridColumnHeader<
  TrackingExceptionsGridColumn,
  TrackingExceptionsGridColumnKey
>({
  layout: TRACKING_EXCEPTIONS_HEADER_LAYOUT,
  defaultColumns: TRACKING_EXCEPTIONS_GRID_COLUMNS,
  tableId: 'tracking-exceptions',
});
