'use client';

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  TRACKING_EXCEPTIONS_GRID_COLUMNS,
  TRACKING_EXCEPTIONS_GRID_FROZEN_CELL,
  isTrackingExceptionsGridFrozen,
  isTrackingExceptionsGridSortable,
  trackingExceptionsGridCell,
  trackingExceptionsGridFrozenLeft,
  trackingExceptionsGridRowShellClass,
  trackingExceptionsGridTemplate,
  type TrackingExceptionsGridColumn,
  type TrackingExceptionsGridColumnKey,
} from './tracking-exceptions-grid-layout';

const TRACKING_EXCEPTIONS_HEADER_LAYOUT: LedgerHeaderLayoutApi<TrackingExceptionsGridColumn> = {
  template: trackingExceptionsGridTemplate,
  cellClass: trackingExceptionsGridCell,
  rowShellClass: trackingExceptionsGridRowShellClass,
  frozenCellClass: TRACKING_EXCEPTIONS_GRID_FROZEN_CELL,
  frozenLeft: (key) => trackingExceptionsGridFrozenLeft(key as TrackingExceptionsGridColumnKey),
  isFrozen: isTrackingExceptionsGridFrozen,
  isSortable: isTrackingExceptionsGridSortable,
};

/**
 * Sticky column header for the Tracking Exceptions LedgerGrid. Read-only browse —
 * the empty `select` gutter keeps the frozen tracking cell aligned.
 *
 * Generated by {@link makeLedgerGridColumnHeader} — the family supplies the
 * layout + column model, the factory owns the prop plumbing.
 */
export const TrackingExceptionsGridColumnHeader = makeLedgerGridColumnHeader<
  TrackingExceptionsGridColumn,
  TrackingExceptionsGridColumnKey
>({ layout: TRACKING_EXCEPTIONS_HEADER_LAYOUT, defaultColumns: TRACKING_EXCEPTIONS_GRID_COLUMNS });
