'use client';

/**
 * Sticky column headers for the two Review · Catalog link grids — one per
 * column model, both generated by {@link makeLedgerGridColumnHeader}.
 *
 * Read-only browse (`selectMode: 'never'`); the empty `select` gutter keeps the
 * frozen listing cell aligned with every other house grid. Columns arrive
 * already visibility-resolved by the grid mount, so the header, the rows and
 * the CSS template all consume the same list.
 */

import {
  makeLedgerGridColumnHeader,
  type LedgerHeaderLayoutApi,
} from '@/design-system/components/grid';
import {
  CATALOG_LINK_GRID_COLUMNS,
  CATALOG_LINK_GRID_FROZEN_CELL,
  CATALOG_LINK_TABLE_ID,
  catalogLinkGridCell,
  catalogLinkGridFrozenLeft,
  catalogLinkGridRowShellClass,
  catalogLinkGridTemplate,
  isCatalogLinkGridFrozen,
  isCatalogLinkGridSortable,
  type CatalogLinkGridColumn,
  type CatalogLinkGridColumnKey,
} from './catalog-link-grid-layout';
import {
  IMPORT_EXCEPTION_GRID_COLUMNS,
  IMPORT_EXCEPTION_GRID_FROZEN_CELL,
  IMPORT_EXCEPTION_TABLE_ID,
  importExceptionGridCell,
  importExceptionGridFrozenLeft,
  importExceptionGridRowShellClass,
  importExceptionGridTemplate,
  isImportExceptionGridFrozen,
  isImportExceptionGridSortable,
  type ImportExceptionGridColumn,
  type ImportExceptionGridColumnKey,
} from './import-exception-grid-layout';

const CATALOG_LINK_HEADER_LAYOUT: LedgerHeaderLayoutApi<CatalogLinkGridColumn> = {
  template: catalogLinkGridTemplate,
  cellClass: catalogLinkGridCell,
  rowShellClass: catalogLinkGridRowShellClass,
  frozenCellClass: CATALOG_LINK_GRID_FROZEN_CELL,
  frozenLeft: (key) => catalogLinkGridFrozenLeft(key as CatalogLinkGridColumnKey),
  isFrozen: isCatalogLinkGridFrozen,
  isSortable: isCatalogLinkGridSortable,
};

const IMPORT_EXCEPTION_HEADER_LAYOUT: LedgerHeaderLayoutApi<ImportExceptionGridColumn> = {
  template: importExceptionGridTemplate,
  cellClass: importExceptionGridCell,
  rowShellClass: importExceptionGridRowShellClass,
  frozenCellClass: IMPORT_EXCEPTION_GRID_FROZEN_CELL,
  frozenLeft: (key) => importExceptionGridFrozenLeft(key as ImportExceptionGridColumnKey),
  isFrozen: isImportExceptionGridFrozen,
  isSortable: isImportExceptionGridSortable,
};

export const CatalogLinkGridColumnHeader = makeLedgerGridColumnHeader<
  CatalogLinkGridColumn,
  CatalogLinkGridColumnKey
>({
  layout: CATALOG_LINK_HEADER_LAYOUT,
  defaultColumns: CATALOG_LINK_GRID_COLUMNS,
  tableId: CATALOG_LINK_TABLE_ID,
});

export const ImportExceptionGridColumnHeader = makeLedgerGridColumnHeader<
  ImportExceptionGridColumn,
  ImportExceptionGridColumnKey
>({
  layout: IMPORT_EXCEPTION_HEADER_LAYOUT,
  defaultColumns: IMPORT_EXCEPTION_GRID_COLUMNS,
  tableId: IMPORT_EXCEPTION_TABLE_ID,
});
